outdir:
    /path/to/out 

logdir:
    /path/to/log

samples:
    SAMPLE1: /path/to/SAMPLE1.fq.fof
    SAMPLE2: /path/to/SAMPLE2.fq.fof

sniffles_se:
    5

survivor_distance:
    500

threads:
    8

genome:
    /path/to/ref

regions:
    /path/to/regions.bed

vcfanno_conf:
    /path/to/vcfanno_conf.toml
