outdir:
    /path/to/out 

logdir:
    /path/to/log

samples:
    SAMPLE: /path/to/fastq.fof

sniffles_se:
    5

survivor_distance:
    500

threads:
    8

genome:
    /path/to/ref

regions:
    /path/to/regions.bed

vcfanno_lua:
    /path/to/custom_ro_min.lua

vcfanno_conf:
    /path/to/vcfanno_conf.toml
