outdir:
    /path/to/out 

logdir:
    /path/to/log

sniffles_se:
    5

survivor_distance:
    500

#For 10 nodes= 320cpu
threads:
    per_sample: 10 #320/62
    per_chr: 12 #320/25
    all: 320

genome:
    /path/to/ref

regions:
    /path/to/regions.bed

vcfanno_conf_svs:
    /path/to/vcfanno_bed.conf.svs.38.toml

vcfanno_conf_snvs:
    /path/to/vcfanno_bed.conf.snvs.38.toml

samples:
    SAMPLE1: /path/to/SAMPLE1.fq.fof
    SAMPLE2: /path/to/SAMPLE2.fq.fof
