fixed:
    - CHROM
    - POS
    - CHR2
    - END
    - ID
    - REF
    - ALT
    - QUAL
    - FILTER
    - CIPOS
    - CIEND
    - SVLEN
    - SVTYPE
    - STRANDS
    - SUPP
    - gnomad
    - ngc38
    - wgs13k
    - ngclov
    - ens_trans_ov_id
    - ens_exon_ov_id
    - dbvar_ov_id
    - decipher_ov_id
    - right_rmk_id
    - left_rmk_id
    
samples:
    - A002727
    - A008220
    - A008222
    - BGC-0571-17
    - BGC-1000-15
    - BGC-1032861995
    - BGC-MA2578-14
    - BGC-MA2686-14
    - BGC-N001816092533
    - F000891
    - F006378
    - F27JL
    - F43RB
    - F48DP
    - F98BN
    - G000973
    - G008984
    - G011300
    - G012634
    - G012664
    - G013428
    - H011040
    - L011101
    - M26VRJ
    - M47VRL
    - M55JW
    - M65RP
    - NGC00375_01
    - S1031
    - S1032
    - S11_453
    - S11_537
    - S13_23
    - S13_34
    - S14_166
    - S142251
    - S18_1024
    - S19_009
    - S19_017
    - S19_515
    - S19_745
    - S2203
    - S51261
    - S7047
    - S881
    - S9703
    - SMAR01
    - SMAR02
    - SMAR03
    - SP1
    - SP5
    - SP7
    - V100HA
    - V54VT
    - V64SA
    - VWD1047
    - VWD1080
    - VWD1082
    - VWD1108
    - VWD1129
    - VWD1159
    - VWD221
