[[annotation]]
file="/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/gnomad/GRCh38/r2.1.1/gnomad_grch38.AC.AN.AF.sorted.bed.gz"
names=["ss","se","gnom_id"]
columns=[2,3,4]
ops=["self","self","self"]

#[[annotation]]
#file="/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/NGC_V1/GRCh38/NGC.samples.grch38.sorted.merged.bed.gz"
#names=["ngc38_s","ngc38_e","ngc38_ov_id"]
#columns=[2,3,4]
#ops=["self","self","self"]

#[[postannotation]]
#name="overlap_bp"
#fields=["ss","se"]
#op="lua:printOps(ss,se,0)"
#type="String"

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/ensembl/GRCh38/ensembl_grch38.exons.sorted.bed.gz"
names=["ensembl_s","ensembl_e","ensembl_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[postannotation]]
name="query_gnomad"
fields=["ss","se"]
op="lua:printOps(ss,se,1)" #flag:1 for computing query vs database overlap
type="String"

[[postannotation]]
name="gnomad_query"
fields=["ss","se"]
op="lua:printOps(ss,se,2)" #flag:2 for computing db vs query overlap
type="String"
