#GNOMAD
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/gnomad_grch38.AC.AN.AF.sorted.bed.gz"
names=["gnomad_s","gnomad_e","gnomad_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


#NGC38
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/NGC.samples.grch38.sorted.merged.bed.gz"
names=["ngc38_s","ngc38_e","ngc38_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


#NGCLOV
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/NGC.samples.grch37.Liftover.grch38.sorted.merged.bed.gz"
names=["ngclov_s","ngclov_e","ngclov_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


#ENS_TRANS
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/ensembl_grch38.transcript.1000.sorted.merged.bed.gz"
names=["ens_trans_s","ens_trans_e","ens_trans_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


#ENS_EXON
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/ensembl_grch38.exons.50.sorted.merged.bed.gz"
names=["ens_exon_s","ens_exon_e","ens_exon_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


#DBVAR
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/dbvar_grch38.CG.UR.CV.sorted.merged.gz"
names=["dbvar_s","dbvar_e","dbvar_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


#DECIPHER
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/decipher.grch38.sorted.merged.bed.gz"
names=["decipher_s","decipher_e","decipher_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]


