[[annotation]]
file="/home/wdecoster/databases/Homo_sapiens/GRCh38_recommended/GRCh38_full_annotation.bed.gz"
columns = [4]
ops = ["uniq"]
names = ["GENE"]

[[annotation]]
file="/home/wdecoster/databases/Homo_sapiens/GRCh38_recommended/GRCh38_exons.bed.gz"
columns = [4]
ops = ["uniq"]
names = ["CODING"]

[[annotation]]
file="/home/wdecoster/databases/Homo_sapiens/GRCh38_recommended/GRCh38_genomicSuperDups.bed.bgz"
columns = [4]
ops = ["uniq"]
names = ["SEGDUP"]

[[annotation]]
file="/home/wdecoster/databases/Homo_sapiens/GRCh38_recommended/dgv_GRCh38.bed.bgz"
columns = [4]
ops = ["uniq"]
names = ["DGV"]
