##DATABASES
GNOMAD38R3=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources//gnomad/GRCh38/r3.0/byChr/gnomad.genomes.r3.0.sites.chr${CHROM}.vcf.bgz
GNOMAD38R2G=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources//gnomad/GRCh38/r2.1.1/byChr/gnomad.genomes.r2.1.sites.grch38.chr${CHROM}_noVEP.vcf.gz
GNOMAD38R2E=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources//gnomad/GRCh38/r2.1.1/byChr/gnomad.exomes.r2.1.sites.grch38.chr${CHROM}_noVEP.vcf.gz

TOPMED=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources//topmed/GRC38/freeze5/bravo-dbsnp-all_noChr.vcf.gz
CLINVAR=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources//clinvar/hg38/20191202/clinvar_20191202.vcf.gz

CADDSNPS=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/CADD/GRCh38/v1.5/whole_genome_SNVs.tsv.gz
CADDINDELS=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/CADD/GRCh38/v1.5/InDels.tsv.gz
EXACPLI=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/gnomad/gnomad.v2.1.1.lof_metrics.by_transcript_forVEP.txt
REVELPLUG=/rds/project/flr24/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/REVEL/grch38/new_tabbed_revel.sorted.tsv.gz

----------------------

#ENS_TRANS
[[annotation]]
file="/rds/project/who1000/rds-who1000-wgs10k/WGS10K/data/projects/nanopore/us/resources/software/vcfanno/GRCh38/ensembl_grch38.transcript.1000.sorted.merged.bed.gz"
fields = ["ID"]
ops=["self"]
names=["topmed_id"]